name: build-and-push
permissions: 
  contents: read
  packages: write
on: 
  workflow_dispatch: 
  push: 
    branches: ["main"]
jobs:
  build-and-push:
    env: 
      TAG: calebryant/cookbook-server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: calebryant
          password: ${{ secrets.DOCKER_PAT }}
      - name: Build and push Docker image
        run: docker build . --tag $TAG:latest && docker push $TAG:latest